### ISSUE TITLE
Datasets and Checkpoints 's link was 404

### ISSUE THREAD

**Issue by minasora** [engkarat/cosine-ood-detector#6]
I am trying to reproduce the results, but it seems that the link to the dataset and pre-trained model on the home page is not working, I would appreciate it if you could update it.

**Comment by engkarat** [comment]
I will fix them. Sorry for the inconvenience.

**Comment by engkarat** [comment]
I have fixed the link and updated the code to be compatible with python 3.7. Please try and let me know if you have any feedback. Thank you so much!!

**Comment by minasora** [comment]
It worked well, Thank you for your hard work! Great idea and excellent work!
